### ISSUE TITLE
Add style.less to simplify color change

### ISSUE THREAD

**Issue by ralfjunker** [dokufreaks/plugin-cloud#46]
Here is an example style.less file to simplify color change. Simply save the contents below to a file named "style.less" in the "cloud" directory.

``` less
.dokuwiki div.cloud { margin-bottom: 1em; line-height: 200%; font-size: 120%; }

.dokuwiki div.cloud a { padding: 0; margin: 0 0.5ex; }

@l: 10%; /* Percentage to lighten the original color. */
@d: 15%; /* Percentage to desaturate the original color. */

/* Font sizes from largest to smallest font. */
@f5: 210%; @f4: 190%; @f3: 160%; @f2: 130%; @f1: 100%;

@c0: darkblue;
.dokuwiki div.cloud a.cloud1 { font-size: @f1; color: desaturate(lighten(@c0, 4 * @l), 4 * @d); }
.dokuwiki div.cloud a.cloud2 { font-size: @f2; color: desaturate(lighten(@c0, 3 * @l), 3 * @d); }
.dokuwiki div.cloud a.cloud3 { font-size: @f3; color: desaturate(lighten(@c0, 2 * @l), 2 * @d); }
.dokuwiki div.cloud a.cloud4 { font-size: @f4; color: desaturate(lighten(@c0, 1 * @l), 1 * @d); }
.dokuwiki div.cloud a.cloud5 { font-size: @f5; color: @c0; }

@c1: darkgreen;
.dokuwiki div.cloud a.cloud1_tag1 { font-size: @f1; color: desaturate(lighten(@c1, 4 * @l), 4 * @d); }
.dokuwiki div.cloud a.cloud2_tag1 { font-size: @f2; color: desaturate(lighten(@c1, 3 * @l), 3 * @d); }
.dokuwiki div.cloud a.cloud3_tag1 { font-size: @f3; color: desaturate(lighten(@c1, 2 * @l), 2 * @d); }
.dokuwiki div.cloud a.cloud4_tag1 { font-size: @f4; color: desaturate(lighten(@c1, 1 * @l), 1 * @d); }
.dokuwiki div.cloud a.cloud5_tag1 { font-size: @f5; color: @c1; }

@c2: darkred;
.dokuwiki div.cloud a.cloud1_tag2 { font-size: @f1; color: desaturate(lighten(@c2, 4 * @l), 4 * @d); }
.dokuwiki div.cloud a.cloud2_tag2 { font-size: @f2; color: desaturate(lighten(@c2, 3 * @l), 3 * @d); }
.dokuwiki div.cloud a.cloud3_tag2 { font-size: @f3; color: desaturate(lighten(@c2, 2 * @l), 2 * @d); }
.dokuwiki div.cloud a.cloud4_tag2 { font-size: @f4; color: desaturate(lighten(@c2, 1 * @l), 1 * @d); }
.dokuwiki div.cloud a.cloud5_tag2 { font-size: @f5; color: @c2; }
```

Newer DokuWiki versions will pick styles.less over styles.css so the latter may stay in the distribution for compatibility with older DokuWikis.
